server:
  port: 8768

eureka:
  client:
    service-url:
      url: http://localhost:8761/eureka/

spring:
  application:
    name: zuui-server
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consume
    api-b:
      path: /api-b/**
      serviceId: feign-server

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000